[CY-10243] asciicast support for guac
cyolosecurity/guacamole-server pull request #2
Opened 2023-11-23 12:38 UTC by amityahav

- Added support for asciicast recording in guacd's SSH proxy. the same logic that is implemented in the native SSH is also applied here.

Tested locally

2023-11-23 12:39 UTC, amityahav commented on src/libguac/guacamole/recording.h
> +
just moved

2023-11-23 14:55 UTC, Virviil commented on src/libguac/timestamp.c
> +}
```suggestion
}

```

2023-11-23 15:19 UTC, Virviil requested changes

2023-11-23 15:19 UTC, Virviil commented on src/common-ssh/asciicast.c
> +    end:
Please check free sequeences here also

2023-11-23 15:19 UTC, Virviil commented on src/common-ssh/asciicast.c
> +}
```suggestion
}

```

2023-11-23 15:19 UTC, Virviil commented on src/common-ssh/common-ssh/asciicast.h
> +#endif
```suggestion
#endif

```

2023-11-23 15:19 UTC, Virviil commented on src/protocols/ssh/ssh.c
> +}
```suggestion
}

```

2023-11-26 14:04 UTC, Virviil approved these changes

2023-11-29 08:22 UTC, merged